# Generated by Django 2.2.4 on 2019-09-02 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(
                    max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(
                    max_length=50, verbose_name='Last Name')),
                ('creation_time', models.DateTimeField(
                    verbose_name='Creation Date')),
                ('modification_time', models.DateTimeField(
                    verbose_name='Modification Date')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(
                    max_length=50, verbose_name='User Name')),
                ('password', models.CharField(
                    max_length=50, verbose_name='Password')),
                ('email', models.EmailField(max_length=254,
                                            verbose_name='verbose_name=Email Address')),
                ('creation_time', models.DateTimeField(
                    verbose_name='Creation Date')),
                ('modification_time', models.DateTimeField(
                    verbose_name='Modification Date')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                             to='login.Person', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
